import 'dotenv/config'; import express from 'express'; import cors from 'cors'; import morgan from 'morgan'; import crypto from 'node:crypto'; import PDFDocument from 'pdfkit'; import { z } from 'zod';
import { registry, tenantDb, business } from './db.js'; import { hash, checkPassword, token, requireAuth, allow } from './auth.js';
const app=express(); app.use(cors()); app.use(express.json()); app.use(morgan('tiny')); const id=()=>crypto.randomUUID(); const now=()=>new Date().toISOString();
function tenant(req,res,next){ const b=business(req.user.businessId); if(!b?.active) return res.status(403).json({error:'Business inactive'}); req.business=b; req.db=tenantDb(b.db_name); next(); }
function log(req, action, detail=''){ req.db?.prepare('INSERT INTO activity_logs VALUES (?,?,?,?,CURRENT_TIMESTAMP)').run(id(),req.user.id,action,detail); }
app.post('/api/auth/login',(req,res)=>{ const {email,password}=req.body; const user=registry.prepare('SELECT * FROM users WHERE lower(email)=lower(?)').get(email||''); if(!user || !checkPassword(password||'',user.password_hash)) return res.status(401).json({error:'Invalid email or password'}); if(!user.active || (user.business_id && !business(user.business_id)?.active)) return res.status(403).json({error:'Account or business is inactive'}); res.json({token:token(user),user:{id:user.id,email:user.email,role:user.role,businessId:user.business_id}}); });
app.get('/api/admin/businesses',requireAuth,allow('SUPER_ADMIN'),(req,res)=>res.json(registry.prepare(`SELECT b.*, u.email owner_email, (SELECT count(*) FROM users s WHERE s.business_id=b.id AND s.role='STAFF') staff_count FROM businesses b LEFT JOIN users u ON u.business_id=b.id AND u.role='OWNER' ORDER BY b.created_at DESC`).all()));
app.post('/api/admin/businesses',requireAuth,allow('SUPER_ADMIN'),(req,res)=>{ const v=z.object({name:z.string().min(2),ownerEmail:z.string().email(),ownerPassword:z.string().min(8)}).safeParse(req.body); if(!v.success)return res.status(400).json({error:v.error.issues[0].message}); const businessId=id(), dbName=`business-${businessId}.sqlite`, ownerId=id(); try { registry.transaction(()=>{registry.prepare('INSERT INTO businesses(id,name,db_name) VALUES(?,?,?)').run(businessId,v.data.name,dbName); tenantDb(dbName); registry.prepare('INSERT INTO users(id,business_id,email,password_hash,role) VALUES(?,?,?,?,?)').run(ownerId,businessId,v.data.ownerEmail,hash(v.data.ownerPassword),'OWNER');})(); res.status(201).json({id:businessId,name:v.data.name}); }catch(e){res.status(409).json({error:'Email already exists'});} });
app.patch('/api/admin/businesses/:id',requireAuth,allow('SUPER_ADMIN'),(req,res)=>{ const active=!!req.body.active; const changed=registry.prepare('UPDATE businesses SET active=? WHERE id=?').run(active?1:0,req.params.id); if(!changed.changes)return res.status(404).json({error:'Business not found'}); registry.prepare('UPDATE users SET active=? WHERE business_id=?').run(active?1:0,req.params.id); res.json({ok:true,active}); });
app.get('/api/admin/status',requireAuth,allow('SUPER_ADMIN'),(req,res)=>res.json({businesses:registry.prepare('SELECT count(*) n FROM businesses').get().n,activeBusinesses:registry.prepare('SELECT count(*) n FROM businesses WHERE active=1').get().n,users:registry.prepare('SELECT count(*) n FROM users').get().n}));
app.get('/api/admin/sync-logs',requireAuth,allow('SUPER_ADMIN'),(req,res)=>{const events=[];for(const b of registry.prepare('SELECT id,name,db_name FROM businesses').all()){try{events.push(...tenantDb(b.db_name).prepare('SELECT *,? business_name FROM sync_events ORDER BY created_at DESC LIMIT 20').all(b.name))}catch{}}res.json(events.sort((a,b)=>b.created_at.localeCompare(a.created_at)).slice(0,100))});
app.get('/api/admin/reports',requireAuth,allow('SUPER_ADMIN'),(req,res)=>{const reports=[];for(const b of registry.prepare('SELECT id,name,db_name FROM businesses').all()){try{const total=tenantDb(b.db_name).prepare('SELECT COALESCE(sum(amount),0) total FROM sales WHERE deleted_at IS NULL').get().total;reports.push({businessId:b.id,name:b.name,total})}catch{}}res.json(reports)});
app.use('/api',requireAuth,tenant);
app.get('/api/me',(req,res)=>res.json({business:req.business,user:registry.prepare('SELECT id,email,role,active FROM users WHERE id=?').get(req.user.id)}));
app.get('/api/sales',(req,res)=>{const rows=req.db.prepare('SELECT * FROM sales WHERE deleted_at IS NULL ORDER BY sold_at DESC').all();res.json(rows)});
app.post('/api/sales',(req,res)=>{const v=z.object({id:z.string().optional(),amount:z.number().positive(),note:z.string().max(250).optional(),soldAt:z.string().datetime().optional()}).safeParse(req.body);if(!v.success)return res.status(400).json({error:'Valid positive amount required'});const sale={id:v.data.id||id(),amount:v.data.amount,note:v.data.note||'',soldAt:v.data.soldAt||now()};req.db.prepare('INSERT INTO sales(id,amount,note,sold_at,created_by,updated_at) VALUES(?,?,?,?,?,?)').run(sale.id,sale.amount,sale.note,sale.soldAt,req.user.id,now());log(req,'SALE_CREATED',sale.id);res.status(201).json(sale)});
app.put('/api/sales/:id',allow('OWNER'),(req,res)=>{const v=z.object({amount:z.number().positive(),note:z.string().max(250).optional(),soldAt:z.string().datetime()}).safeParse(req.body);if(!v.success)return res.status(400).json({error:'Invalid sale'});const r=req.db.prepare('UPDATE sales SET amount=?,note=?,sold_at=?,updated_at=?,version=version+1 WHERE id=? AND deleted_at IS NULL').run(v.data.amount,v.data.note||'',v.data.soldAt,now(),req.params.id);if(!r.changes)return res.status(404).json({error:'Sale not found'});log(req,'SALE_UPDATED',req.params.id);res.json({ok:true})});
app.delete('/api/sales/:id',allow('OWNER'),(req,res)=>{const r=req.db.prepare('UPDATE sales SET deleted_at=?,updated_at=? WHERE id=? AND deleted_at IS NULL').run(now(),now(),req.params.id);if(!r.changes)return res.status(404).json({error:'Sale not found'});log(req,'SALE_DELETED',req.params.id);res.json({ok:true})});
app.get('/api/summary',(req,res)=>{const d=req.db;res.json({today:d.prepare("SELECT COALESCE(sum(amount),0) total FROM sales WHERE deleted_at IS NULL AND date(sold_at,'localtime')=date('now','localtime')").get().total,month:d.prepare("SELECT COALESCE(sum(amount),0) total FROM sales WHERE deleted_at IS NULL AND strftime('%Y-%m',sold_at)=strftime('%Y-%m','now')").get().total,bars:d.prepare("SELECT date(sold_at) date,sum(amount) total FROM sales WHERE deleted_at IS NULL AND sold_at >= date('now','-6 days') GROUP BY date(sold_at) ORDER BY date").all()})});
app.get('/api/staff',allow('OWNER'),(req,res)=>res.json(registry.prepare("SELECT id,email,active,created_at FROM users WHERE business_id=? AND role='STAFF'").all(req.user.businessId)));
app.post('/api/staff',allow('OWNER'),(req,res)=>{const v=z.object({email:z.string().email(),password:z.string().min(8)}).safeParse(req.body);if(!v.success)return res.status(400).json({error:v.error.issues[0].message});try{registry.prepare('INSERT INTO users(id,business_id,email,password_hash,role) VALUES(?,?,?,?,?)').run(id(),req.user.businessId,v.data.email,hash(v.data.password),'STAFF');res.status(201).json({ok:true})}catch{res.status(409).json({error:'Email already exists'})}});
app.patch('/api/staff/:id',allow('OWNER'),(req,res)=>{const v=z.object({active:z.boolean().optional(),password:z.string().min(8).optional()}).safeParse(req.body);if(!v.success)return res.status(400).json({error:'Invalid change'});const fields=[],vals=[];if(v.data.active!==undefined){fields.push('active=?');vals.push(v.data.active?1:0)}if(v.data.password){fields.push('password_hash=?');vals.push(hash(v.data.password))}if(!fields.length)return res.status(400).json({error:'No change supplied'});vals.push(req.params.id,req.user.businessId);const r=registry.prepare(`UPDATE users SET ${fields.join(',')} WHERE id=? AND business_id=? AND role='STAFF'`).run(...vals);if(!r.changes)return res.status(404).json({error:'Staff member not found'});res.json({ok:true})});
app.post('/api/sync', (req,res)=>{const changes=Array.isArray(req.body.changes)?req.body.changes:[];let accepted=0;for(const c of changes){try{if(c.type==='create'){req.db.prepare('INSERT OR IGNORE INTO sales(id,amount,note,sold_at,created_by,updated_at) VALUES(?,?,?,?,?,?)').run(c.sale.id,c.sale.amount,c.sale.note||'',c.sale.soldAt,req.user.id,c.sale.updatedAt||now());accepted++}else if(c.type==='delete'&&req.user.role==='OWNER'){req.db.prepare('UPDATE sales SET deleted_at=?,updated_at=? WHERE id=?').run(now(),now(),c.sale.id);accepted++}}catch{}}req.db.prepare('INSERT INTO sync_events VALUES(?,?,?,?,CURRENT_TIMESTAMP)').run(id(),req.body.deviceId||null,'SUCCESS',`${accepted}/${changes.length} changes`);res.json({accepted,serverTime:now(),sales:req.db.prepare('SELECT * FROM sales WHERE deleted_at IS NULL').all()})});
app.get('/api/report.pdf',(req,res)=>{const sales=req.db.prepare('SELECT * FROM sales WHERE deleted_at IS NULL ORDER BY sold_at DESC').all();const total=sales.reduce((n,s)=>n+s.amount,0);res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition','attachment; filename=sales-report.pdf');const pdf=new PDFDocument();pdf.pipe(res);pdf.fontSize(20).text(`${req.business.name} — Sales Report`);pdf.moveDown().fontSize(12).text(`Generated ${new Date().toLocaleString()}`);pdf.moveDown().text(`Total sales: ${total.toFixed(2)}`);pdf.moveDown();sales.forEach(s=>pdf.text(`${new Date(s.sold_at).toLocaleDateString()}  |  ${s.amount.toFixed(2)}  |  ${s.note}`));pdf.end()});
app.get('/health',(req,res)=>res.json({ok:true})); app.listen(process.env.PORT||4000,()=>console.log('API listening'));
