import 'dotenv/config';import express from'express';import cors from'cors';import morgan from'morgan';import crypto from'node:crypto';import PDFDocument from'pdfkit';import{z}from'zod';import{registry,tenantDb,encrypt,decrypt}from'./db.js';import{hash,checkPassword,token,requireAuth,allow}from'./auth.js';
const app=express(),id=()=>crypto.randomUUID(),now=()=>new Date().toISOString();app.use(cors());app.use(express.json());app.use(morgan('tiny'));
async function tenant(req,res,next){try{const r=await registry(),business=await r.collection('businesses').findOne({id:req.user.businessId,active:true});if(!business)return res.status(403).json({error:'Business is inactive'});req.business=business;req.db=await tenantDb(decrypt(business.encryptedMongoUri),business.tenantDatabaseName);next()}catch(e){res.status(500).json({error:'Tenant connection unavailable'})}}
async function log(req,action,detail=''){await req.db.collection('activity_logs').insertOne({id:id(),actorId:req.user.id,action,detail,createdAt:now()})}
app.post('/api/auth/login',async(req,res)=>{try{const {email,password}=req.body,r=await registry();let user=await r.collection('users').findOne({email:(email||'').toLowerCase(),role:'SUPER_ADMIN'});if(user){if(!user.active||!checkPassword(password||'',user.passwordHash))return res.status(401).json({error:'Invalid email or password'});return res.json({token:token(user),user:{id:user.id,email:user.email,role:user.role,businessId:null}})}const lookup=await r.collection('user_lookup').findOne({email:(email||'').toLowerCase()});const business=lookup&&await r.collection('businesses').findOne({id:lookup.businessId});if(!lookup||!business?.active||!lookup.active)return res.status(401).json({error:'Invalid email or password'});const db=await tenantDb(decrypt(business.encryptedMongoUri),business.tenantDatabaseName);user=await db.collection('users').findOne({id:lookup.id,active:true});if(!user||!checkPassword(password||'',user.passwordHash))return res.status(401).json({error:'Invalid email or password'});res.json({token:token(user),user:{id:user.id,email:user.email,role:user.role,businessId:user.businessId}})}catch{res.status(503).json({error:'Login service unavailable'})}});
app.get('/api/admin/businesses',requireAuth,allow('SUPER_ADMIN'),async(req,res)=>{const r=await registry(),rows=await r.collection('businesses').find({}).sort({createdAt:-1}).toArray();const result=await Promise.all(rows.map(async b=>{const staff=await r.collection('user_lookup').countDocuments({businessId:b.id,role:'STAFF'});const owner=await r.collection('user_lookup').findOne({businessId:b.id,role:'OWNER'});return{id:b.id,name:b.name,active:b.active,created_at:b.createdAt,owner_email:owner?.email,staff_count:staff,tenant_database:b.tenantDatabaseName}}));res.json(result)});
app.post('/api/admin/businesses',requireAuth,allow('SUPER_ADMIN'),async(req,res)=>{const v=z.object({name:z.string().min(2),ownerEmail:z.string().email(),ownerPassword:z.string().min(8),tenantMongoUri:z.string().min(20),tenantDatabaseName:z.string().min(1).max(64).regex(/^[A-Za-z0-9_-]+$/)}).safeParse(req.body);if(!v.success)return res.status(400).json({error:v.error.issues[0].message});const r=await registry(),businessId=id(),ownerId=id();try{const db=await tenantDb(v.data.tenantMongoUri,v.data.tenantDatabaseName);await db.collection('users').insertOne({id:ownerId,businessId,email:v.data.ownerEmail.toLowerCase(),passwordHash:hash(v.data.ownerPassword),role:'OWNER',active:true,createdAt:now()});await r.collection('businesses').insertOne({id:businessId,name:v.data.name,active:true,encryptedMongoUri:encrypt(v.data.tenantMongoUri),tenantDatabaseName:v.data.tenantDatabaseName,createdAt:now()});await r.collection('user_lookup').insertOne({id:ownerId,businessId,email:v.data.ownerEmail.toLowerCase(),role:'OWNER',active:true});res.status(201).json({id:businessId,name:v.data.name})}catch(e){res.status(409).json({error:'Could not connect to that database or owner email already exists'})}});
app.patch('/api/admin/businesses/:id',requireAuth,allow('SUPER_ADMIN'),async(req,res)=>{const r=await registry(),active=!!req.body.active,result=await r.collection('businesses').updateOne({id:req.params.id},{$set:{active}});if(!result.matchedCount)return res.status(404).json({error:'Business not found'});await r.collection('user_lookup').updateMany({businessId:req.params.id},{$set:{active}});res.json({ok:true,active})});
app.get('/api/admin/status',requireAuth,allow('SUPER_ADMIN'),async(req,res)=>{const r=await registry();res.json({businesses:await r.collection('businesses').countDocuments(),activeBusinesses:await r.collection('businesses').countDocuments({active:true}),users:await r.collection('user_lookup').countDocuments()+await r.collection('users').countDocuments()})});
app.use('/api',requireAuth,tenant);app.get('/api/me',async(req,res)=>res.json({business:{id:req.business.id,name:req.business.name,active:req.business.active},user:await req.db.collection('users').findOne({id:req.user.id},{projection:{passwordHash:0,_id:0}})}));
app.get('/api/sales',async(req,res)=>res.json(await req.db.collection('sales').find({deletedAt:null}).sort({soldAt:-1}).project({_id:0}).toArray()));
app.post('/api/sales',async(req,res)=>{const v=z.object({id:z.string().optional(),amount:z.number().positive(),note:z.string().max(250).optional(),soldAt:z.string().datetime().optional()}).safeParse(req.body);if(!v.success)return res.status(400).json({error:'Valid positive amount required'});const sale={id:v.data.id||id(),amount:v.data.amount,note:v.data.note||'',soldAt:v.data.soldAt||now(),createdBy:req.user.id,updatedAt:now(),deletedAt:null,version:1};try{await req.db.collection('sales').insertOne(sale);await log(req,'SALE_CREATED',sale.id);res.status(201).json(sale)}catch{res.status(409).json({error:'Sale already exists'})}});
app.put('/api/sales/:id',allow('OWNER'),async(req,res)=>{const v=z.object({amount:z.number().positive(),note:z.string().max(250).optional(),soldAt:z.string().datetime()}).safeParse(req.body);if(!v.success)return res.status(400).json({error:'Invalid sale'});const x=await req.db.collection('sales').updateOne({id:req.params.id,deletedAt:null},{$set:{amount:v.data.amount,note:v.data.note||'',soldAt:v.data.soldAt,updatedAt:now()},$inc:{version:1}});if(!x.matchedCount)return res.status(404).json({error:'Sale not found'});await log(req,'SALE_UPDATED',req.params.id);res.json({ok:true})});
app.delete('/api/sales/:id',allow('OWNER'),async(req,res)=>{const x=await req.db.collection('sales').updateOne({id:req.params.id,deletedAt:null},{$set:{deletedAt:now(),updatedAt:now()}});if(!x.matchedCount)return res.status(404).json({error:'Sale not found'});await log(req,'SALE_DELETED',req.params.id);res.json({ok:true})});
app.get('/api/summary',async(req,res)=>{const rows=await req.db.collection('sales').find({deletedAt:null}).toArray(),date=new Date(),today=date.toDateString(),month=date.getMonth(),year=date.getFullYear(),total=list=>list.reduce((n,x)=>n+x.amount,0),bars=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);bars.push({date:d.toISOString().slice(0,10),total:total(rows.filter(x=>new Date(x.soldAt).toDateString()===d.toDateString()))})}res.json({today:total(rows.filter(x=>new Date(x.soldAt).toDateString()===today)),month:total(rows.filter(x=>{const d=new Date(x.soldAt);return d.getMonth()===month&&d.getFullYear()===year})),bars})});
app.get('/api/staff',allow('OWNER'),async(req,res)=>res.json(await req.db.collection('users').find({businessId:req.user.businessId,role:'STAFF'},{projection:{_id:0,passwordHash:0}}).toArray()));
app.post('/api/staff',allow('OWNER'),async(req,res)=>{const v=z.object({email:z.string().email(),password:z.string().min(8)}).safeParse(req.body);if(!v.success)return res.status(400).json({error:v.error.issues[0].message});const r=await registry(),staff={id:id(),businessId:req.user.businessId,email:v.data.email.toLowerCase(),passwordHash:hash(v.data.password),role:'STAFF',active:true,createdAt:now()};try{await req.db.collection('users').insertOne(staff);await r.collection('user_lookup').insertOne({id:staff.id,businessId:staff.businessId,email:staff.email,role:'STAFF',active:true});res.status(201).json({ok:true})}catch{res.status(409).json({error:'Email already exists'})}});
app.patch('/api/staff/:id',allow('OWNER'),async(req,res)=>{const v=z.object({active:z.boolean().optional(),password:z.string().min(8).optional()}).safeParse(req.body);if(!v.success)return res.status(400).json({error:'Invalid change'});const update={};if(v.data.active!==undefined)update.active=v.data.active;if(v.data.password)update.passwordHash=hash(v.data.password);if(!Object.keys(update).length)return res.status(400).json({error:'No change supplied'});const x=await req.db.collection('users').updateOne({id:req.params.id,businessId:req.user.businessId,role:'STAFF'},{$set:update});if(!x.matchedCount)return res.status(404).json({error:'Staff member not found'});if(v.data.active!==undefined)await (await registry()).collection('user_lookup').updateOne({id:req.params.id},{$set:{active:v.data.active}});res.json({ok:true})});
app.post('/api/sync',async(req,res)=>{const changes=Array.isArray(req.body.changes)?req.body.changes:[];let accepted=0;for(const c of changes){try{if(c.type==='create'){await req.db.collection('sales').updateOne({id:c.sale.id},{$setOnInsert:{id:c.sale.id,amount:c.sale.amount,note:c.sale.note||'',soldAt:c.sale.soldAt,createdBy:req.user.id,updatedAt:c.sale.updatedAt||now(),deletedAt:null,version:1}},{upsert:true});accepted++}if(c.type==='delete'&&req.user.role==='OWNER'){await req.db.collection('sales').updateOne({id:c.sale.id},{$set:{deletedAt:now(),updatedAt:now()}});accepted++}}catch{}}await req.db.collection('sync_events').insertOne({id:id(),deviceId:req.body.deviceId||null,status:'SUCCESS',detail:`${accepted}/${changes.length} changes`,createdAt:now()});res.json({accepted,serverTime:now(),sales:await req.db.collection('sales').find({deletedAt:null}).project({_id:0}).toArray()})});
app.get('/api/report.pdf',async(req,res)=>{const sales=await req.db.collection('sales').find({deletedAt:null}).sort({soldAt:-1}).toArray(),total=sales.reduce((n,s)=>n+s.amount,0);res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition','attachment; filename=sales-report.pdf');const pdf=new PDFDocument();pdf.pipe(res);pdf.fontSize(20).text(`${req.business.name} — Sales Report`).moveDown().fontSize(12).text(`Generated ${new Date().toLocaleString()}`).moveDown().text(`Total sales: ${total.toFixed(2)}`).moveDown();sales.forEach(s=>pdf.text(`${new Date(s.soldAt).toLocaleDateString()} | ${s.amount.toFixed(2)} | ${s.note}`));pdf.end()});
app.get('/health',(req,res)=>res.json({ok:true}));if(!process.env.VERCEL)app.listen(process.env.PORT||4000,()=>console.log('API listening'));export default app;
